### ISSUE TITLE
SortableCollection is not defined

### ISSUE THREAD

**Issue by whiskeysauer** [kjantzer/backbone-list-controller#6]
I am getting SortableCollection is not defined. I don't see it listed in the dependencies. I see another project with that name, bit looks old. What's a "SortableCollection"? Is this a native backbone object? If I use `require('backbone-list-controller');` then Browserify reports...  Cannot find module 'jit-grunt' from 'C:\xxxxxx\xxxxx-projects\prjxxxxxxx\node_modules\backbone-list-controller'

This looks like a pretty cool way to implement an infinite scroll, but I've not found a way yet to get it to work with Browserify.

**Comment by kjantzer** [comment]
`SortableCollection` is defined here https://github.com/kjantzer/backbone-list-controller/blob/master/src/SortableCollection.js

This library hasn't been modularized for require.js or commonjs (browserfiy). It currently creates globals on the `window`

**Comment by kjantzer** [comment]
If you only need infinite scroll and not the use of filters, I'd suggest looking for something more light weight and simpler.

**Comment by whiskeysauer** [comment]
Thanks for the clarification. I found something that I think will work. Closing..
